"""
Seed script: migrate all hardcoded chapters from Dashboard.jsx into MongoDB.
Run once:  python seed_chapters.py
Safe to re-run — uses upsert by chapter id.
"""
import asyncio
import os
from pathlib import Path
from dotenv import load_dotenv
from motor.motor_asyncio import AsyncIOMotorClient

ROOT_DIR = Path(__file__).parent
load_dotenv(ROOT_DIR / '.env', override=True)

CHAPTERS = [
    {
        "id": 0,
        "type": "static",
        "order": 0,
        "code": "INTRO - LO WAJIB NONTON DULU SEBELUM LANJUT KE CHAPTER LAIN!",
        "title": "Introduction",
        "icon_name": "Play",
        "color": "from-orange-500/20 to-orange-500/5",
        "accent": "text-orange-400",
        "border": "border-orange-500/30",
        "badge": "bg-orange-500/20 text-orange-400",
        "locked": False,
        "comingSoon": False,
        "visible": True,
        "lessons": [
            {
                "id": "0-1",
                "type": "video",
                "title": "Intro — Tonton Ini Dulu!",
                "duration": "5 min",
                "content": [
                    {"type": "image", "src": "/intro-philip.webp", "alt": "Philip Vasquez"},
                    {"type": "callout", "icon": "👋", "text": "Sebelum lo mulai ke chapter-chapter lain, lo wajib nonton ini dulu, biar lo paham tujuan course ini untuk apa."},
                    {"type": "video_embed", "src": "https://www.youtube.com/embed/qM87IZH3w38"},
                ],
            }
        ],
    },
    {
        "id": 1,
        "type": "static",
        "order": 1,
        "code": "MINDSET",
        "title": "Have This MINDSET",
        "icon_name": "Brain",
        "color": "from-purple-500/20 to-purple-500/5",
        "accent": "text-purple-400",
        "border": "border-purple-500/30",
        "badge": "bg-purple-500/20 text-purple-400",
        "locked": False,
        "comingSoon": False,
        "visible": True,
        "lessons": [
            {
                "id": "1-1",
                "type": "text",
                "title": "Have This MINDSET",
                "duration": "10 min baca",
                "content": [
                    {"type": "image", "src": "/ch1-philip.webp", "alt": "Philip Vasquez"},
                    {"type": "callout", "icon": "🎯", "text": "Goal: Ngubah mindset lo biar bisa tetap on track ke progress gym lo"},
                    {"type": "text", "text": "**CHAPTER INI WAJIB LO BACA DAN GA BOLEH SKIP!**"},
                    {"type": "text", "text": "Percaya ama gw, mau sejago apapun lo…"},
                    {"type": "text", "text": "tapi kalau mindset lo udah salah, apapun lo lakuin juga bakalan ngaco."},
                    {"type": "text", "text": "Dan banyak banget orang yang punya mindset keliru soal bentukin otot, yang ujungnya cuman bikin mereka stuck dan ga berkembang."},
                    {"type": "text", "text": "Di *chapter* ini, gw bakalan spill semua mindset yang harus lo \"***AVOID***\" biar progress lu lebih lancar."},
                    {"type": "heading2", "text": "1. Train Otot - Failure Bikin Otot Growth?"},
                    {"type": "text", "text": "Banyak yang mikir kalau \"*Train To Failure*\" itu bisa bentukin otot."},
                    {"type": "text", "text": "Jawabannya: bisa iya, bisa engga."},
                    {"type": "text", "text": "Loh kok bisa bang? Sini gw jelasin biar lo paham apa yang gw maksud."},
                    {"type": "text", "text": "Sebelumnya gw pengen lo paham apa arti dari *Train To Failure* itu apa: Basically, *Train to failure* itu artinya lo ngelakuin repetisi sampai gak bisa angkat lagi dengan form yang benar."},
                    {"type": "heading3", "text": "Kenapa Failure Bisa Bikin Otot Tumbuh?"},
                    {"type": "text", "text": "Otot tumbuh karena 3 hal utama:"},
                    {"type": "numbered", "items": ["*Mechanical tension* (beban berat)", "*Metabolic stress* (*pump, burn*)", "*Muscle fiber recruitment* (aktivasi serabut otot maksimal)"]},
                    {"type": "text", "text": "Artinya…."},
                    {"type": "text", "text": "Semakin dekat ke *failure* → semakin banyak serabut (*muscle spindles*) otot aktif → *stimulus* (rangsangan ke otot) makin besar."},
                    {"type": "text", "text": "\"Ya berarti harus selalu *failure* dong?\""},
                    {"type": "text", "text": "Tunggu dulu. Ini baru mau gw jelasin:"},
                    {"type": "text", "text": "*Failure* itu bikin stimulus tinggi, tapi juga bikin *fatigue* juga tinggi."},
                    {"type": "text", "text": "Dan *muscle growth* itu bukan cuma soal stimulus, tapi soal rasio stimulus dibanding fatigue."},
                    {"type": "text", "text": "Kalau lu failure terus tiap set, tiap latihan, tiap minggu… Ya ambyarr, otot lu jadinya ga ke recover."},
                    {"type": "text", "text": "Jadi gausah train to failure dong? Ya tergantung tujuan lo mau gimana: *Hypertrophy* kah? *Strength*? Atau *Endurance*?"},
                    {"type": "text", "text": "Cuman gw yakin 99% dari kalian yang join course ini ya pasti mau bentukin otot, so gw bakalan lebih reccomend kalian untuk train RIR 1-3. Untuk detailnya gw ada jelasin di chapter \"***How To Build Your Muscle***\"."},
                    {"type": "text", "text": "So ini cuman biar lo kebayang aja dan ga salah kaprah soal ***Train To Failure*** ini."},
                    {"type": "heading2", "text": "2. Instant Mentality"},
                    {"type": "text", "text": "Sangking banyaknya konten-konten yang show off badan mereka jadi cuman dalam waktu singkat, dan akhirnya banyak yang jadi kepengen bentukin badan (***FOMO***). Padahal bisa aja influencer yang mereka tontonin lagi make **Roid** atau apapun itu."},
                    {"type": "text", "text": "Biasanya mereka bandingin progress natural mereka dengan progress orang yang mungkin nggak natural. Endingnya apa? Ya langsung stop nge-gym."},
                    {"type": "text", "text": "Karena mereka *expect* dalam waktu singkat bisa langsung dapet otot gede cuman dalam waktu 1 minggu. Padahal ya ga gitu…"},
                    {"type": "text", "text": "**Perkembangan otot itu biasanya 0.5kg - 0.9kg per bulan, kalau lo memang masih baru awal ngegym. Tapi kalau untuk level intermediate - advance itu dari 0.25kg - 0.5kg per bulan aja biasanya. [*Source*](https://www.bodyspec.com/blog/post/the_complete_guide_to_newbie_gains)**"},
                    {"type": "text", "text": "Dan perkembangan otot itu tergantung dari cara lo konsumsi makanan, latihan, dan tidur."},
                    {"type": "text", "text": "**Jadi** kalau lo memang mau gedein otot lo, coba deh *optimize* dari 3 itu dulu."},
                    {"type": "text", "text": "Tapi masalahnya bukan cuma soal pemahaman soal latihan, nutrisi, dan lain-lain. Tapi di *mentality* nya."},
                    {"type": "text", "text": "Gw punya banyak temen yang pengen ikut gw ngegym, *most of them* ga tahan sampe 1 minggu, dan dari semua yang ikut gw, yang paling lama bertahan cuman 1 bulan. *Why?* Karena yang mereka dapet cuman pain-nya doang dan hasil yang mereka pengen ga ada."},
                    {"type": "text", "text": "*Instant mentality* ini malah bikin lo nge-stuck cuman gara gara lo ga mau berprogres, percaya deh ama gw, setelah 1-2 minggu lo latihan, rasa sakitnya itu bakalan menghilang dengan sendirinya."},
                    {"type": "text", "text": "Karena otot lo udah *recovery* & beradaptasi."},
                    {"type": "text", "text": "*One thing that you need to remember is:*"},
                    {"type": "heading3", "text": "Proccess Is Not Your Enemy."},
                    {"type": "heading2", "text": "3. Gym Lebih Lama ≠ Progress"},
                    {"type": "text", "text": "Banyak yang ngira kalau gym 2-3 jam = otot makin gede."},
                    {"type": "text", "text": "**Faktanya** otot kalau lu train selama itu, yang ada dapet pain-nya doang, gain-nya kaga ada."},
                    {"type": "text", "text": "Karena muscle growth itu bukan soal seberapa lama lo di gym, tapi soal **stimulus yang berkualitas + recovery yang cukup.** [*Source*](https://pubmed.ncbi.nlm.nih.gov/36248475/)"},
                    {"type": "text", "text": "Dalam *hypertrophy*, waktu latihan paling ideal adalah **45 - 90 menit per sesi.**"},
                    {"type": "text", "text": "Dan *make sure* kalau lagi latihan, kamu harus bener-bener fokus dan ga buang-buang waktu lo di gym, biar progress lo bisa **lebih bagus**."},
                    {"type": "heading2", "text": "4. Supplementation Over Everything"},
                    {"type": "quote", "text": "\"Kalau mau bentukin otot harus pakai suplemen dulu\""},
                    {"type": "text", "text": "Kata siapa? Gw masih bisa bentukin otot tanpa suplemen, kecuali **creatine & omega 3.**"},
                    {"type": "image", "src": "/ch1-vincent.webp", "alt": "Vincent di gym", "fit": "contain"},
                    {"type": "text", "text": "Sebelumnya, lo harus paham dulu definisi suplemen itu apa."},
                    {"type": "text", "text": "**Suplemen** itu produk yang dirancang untuk melengkapi kebutuhan zat gizi (vitamin, mineral, asam amino, herbal) guna memelihara, meningkatkan, atau memperbaiki fungsi kesehatan dan daya tahan tubuh. [Source](https://www.halodoc.com/artikel/suplemen-makanan-manfaat-dan-tips-memilih-yang-tepat)"},
                    {"type": "text", "text": "***MEANS*** kalau lo udah mencukupi nutrisi lo dari real food, ya lu ga perlu suplementasi lagi."},
                    {"type": "text", "text": "Kecuali kalau kebutuhan nutrisi lo kurang, lo bisa pakai suplemen untuk memenuhi itu."},
                    {"type": "text", "text": "\"Terus bang Vincent emangnya ga pakai suplemen sama sekali?\""},
                    {"type": "text", "text": "Gw pakai. Tapi yang gw pakai cuman *creatine* dan juga suplemen *omega 3* (karena malas masak & ngolah ikan hehe)."},
                    {"type": "text", "text": "*The reason why* gw pakai *creatine*: Kalau mau dapet *creatine* 5gr setiap hari, *it means* gw harus makan daging sapi 1kg setiap hari & kalau gw makan tiap hari 1kg sapi, yang ada boncos."},
                    {"type": "text", "text": "Jadi ya bukan suplemen itu ga boleh, boleh-boleh aja sebenarnya. Selagi nutrisi lo itu memang tidak tercukupi seperti yang gw sebut di atas."},
                    {"type": "text", "text": "Kalau ***goals*** lo memang mau bentukin otot: banyakin protein dari real food, tidur, dan latihan yang bener. Itu udah lebih dari cukup."},
                    {"type": "heading2", "text": "5. Healthy Lifestyle Harus Jadi Habit"},
                    {"type": "text", "text": "Percaya ama gw…"},
                    {"type": "text", "text": "Salah satu hal yang bakalan lo syukuri & terimakasih ke diri lo di masa depan adalah investasi ke kesehatan, dan jujur aja, gw udah ngelakuin ini dari umur 14-15 tahun sampai umur gw yang sekarang 19 tahun. Alasannya simple: di masa tua nanti, gw masih punya **tenaga & ga banyak penyakit.**"},
                    {"type": "text", "text": "Kalau gw sehat:"},
                    {"type": "list", "items": ["Gw masih bisa **belajar**.", "Gw masih bisa **ngumpul bareng temen.**", "Gw masih bisa **ngumpul sama keluarga.**", "Gw masih bisa **ngelakuin aktivitas yang gw suka.**", "Dan gw masih **kuat untuk jalan-jalan bareng anak gw di masa depan nanti.**"]},
                    {"type": "text", "text": "Kalau gw pengen semua itu = **gw harus jaga kesehatan & bentukin otot dari pas masih muda.**"},
                    {"type": "heading2", "text": "Kapan Waktu Terbaik Untuk Bentukin Otot?"},
                    {"type": "text", "text": "Sekarang!"},
                    {"type": "text", "text": "Sekarang adalah waktu terbaik yang bisa lo manfaatin, karena berat badan lo akan naik seiring berjalannya waktu kalau lo ga gerak sama sekali!"},
                    {"type": "text", "text": "Dan semakin lama lo nunda, makin berat juga buat mulai."},
                    {"type": "text", "text": "Investasi ke kesehatan itu bukan soal keliatan berotot dan *aesthetic* doang."},
                    {"type": "text", "text": "Tapi soal kualitas hidup & *freedom* yang lo dapet di masa depan nanti."},
                    {"type": "text", "text": "*Trust me…* investasi ke kesehatan itu bakaln jadi salah satu hal yang bakalan lo syukuri di hari tua nanti, *so don't waste ur time, and start working out.*"},
                ],
            }
        ],
    },
    {
        "id": 2,
        "type": "static",
        "order": 2,
        "code": "NUTRISI",
        "title": "Nutrition For Muscle & Testosterone",
        "icon_name": "Utensils",
        "color": "from-green-500/20 to-green-500/5",
        "accent": "text-green-400",
        "border": "border-green-500/30",
        "badge": "bg-green-500/20 text-green-400",
        "locked": False,
        "comingSoon": False,
        "visible": True,
        "lessons": [
            {
                "id": "2-1",
                "type": "video",
                "title": "Kebutuhan Nutrisi & Vitamin",
                "duration": "15 min",
                "content": [
                    {"type": "image", "src": "/ch2-philip.webp", "alt": "Philip Vasquez"},
                    {"type": "callout", "icon": "🎯", "text": "GOAL: Lo bisa memahami kebutuhan nutrisi untuk bentukin otot lo"},
                    {"type": "callout", "icon": "⚠️", "text": "**Important Note** ⚠️\n\nGw bukan ahli nutrisi, semua yang gw jelasin di sini *based on experience* yang udah gw jalanin selama beberapa bulan. Kalau kalian ada masalah kesehatan lainnya, please make sure untuk konsul ke dokter atau ke ahli nutrisi dulu untuk kesehatan lo."},
                    {"type": "heading2", "text": "Kebutuhan nutrisi yang lo butuhin"},
                    {"type": "video_embed", "src": "https://www.youtube.com/embed/InFRnBXg3SQ"},
                    {"type": "heading2", "text": "Resources Vitamin"},
                    {"type": "callout", "icon": "💡", "text": "Klik tombol \"▶\" di samping untuk melihat benefit secara penuh."},
                    {"type": "heading2", "text": "1. Vitamin C"},
                    {"type": "accordion", "title": "Benefit Vitamin C", "items": ["Bantu ningkatin imun tubuh", "Bantu produksi collagen", "Bantu recovery tubuh & otot", "Bantu penyerapan zat besi (produksi energi, mendukung sistem kekebalan tubuh, meningkatkan konsentrasi, serta mencegah anemia defisiensi besi)"]},
                    {"type": "heading3", "text": "Sumber Vitamin C"},
                    {"type": "list", "items": ["Jeruk", "Kiwi", "Strawberry", "Paprika merah", "Brokoli", "Bayam", "Jambu biji (**Very High Vit C**)"]},
                    {"type": "text", "text": "Kalau lo makan **sayur hijau + buah**, biasanya vitamin C udah aman."},
                    {"type": "heading2", "text": "2. Vitamin B Complex"},
                    {"type": "accordion", "title": "Benefit Vitamin B Complex", "items": ["Vitamin B ini ada banyak: B1, B2, B3, B5, B6, B7, B9, & B12", "Meningkatkan metabolisme energi", "Mendukung kesehatan otak", "Produksi sel darah merah", "Performa saraf"]},
                    {"type": "heading3", "text": "Sumber Vitamin B Complex"},
                    {"type": "list", "items": ["Daging sapi", "Ayam", "Ikan", "Telur", "Oatmeal", "Nasi merah", "Alpukat", "Pisang", "Sayuran hijau"]},
                    {"type": "heading2", "text": "3. Vitamin D"},
                    {"type": "accordion", "title": "Benefit Vitamin D", "items": ["Kesehatan tulang", "Fungsi imun tubuh", "Produksi hormon", "Kekuatan otot (*strength*)"]},
                    {"type": "heading3", "text": "Sumber Vitamin D"},
                    {"type": "list", "items": ["Matahari", "Salmon", "Sardine", "Tuna", "Telur (terutama kuningnya)", "Jamur tertentu (shitake / maitake)", "Susu yang difortifikasi vitamin D"]},
                    {"type": "text", "text": "Kalau lo rutin makan **ikan + telur**, biasanya kebutuhan vitamin D udah lumayan kebantu."},
                    {"type": "callout", "icon": "☀️", "text": "**Recommendations:** Paparin tubuh lo ke sinar matahari langsung di jam 8/9 pagi ATAU jam 4/5 sore selama 10-15 menit."},
                    {"type": "heading2", "text": "4. Vitamin K"},
                    {"type": "accordion", "title": "Benefit Vitamin K", "items": ["Meminimalisir pendarahan berlebih kalau terluka", "Kesehatan tulang", "Kesehatan jantung"]},
                    {"type": "heading3", "text": "Sumber Vitamin K"},
                    {"type": "text", "text": "**Vitamin K1 (Nabati):**"},
                    {"type": "list", "items": ["Bayam", "Kale", "Brokoli", "Sawi hijau"]},
                    {"type": "text", "text": "**Vitamin K2 (Hewani):**"},
                    {"type": "list", "items": ["Natto", "Keju", "Telur", "Daging"]},
                    {"type": "text", "text": "Kalau lo makan **sayuran hijau + telur / daging**, biasanya vitamin K udah ke-cover."},
                    {"type": "heading2", "text": "5. Vitamin E"},
                    {"type": "accordion", "title": "Benefit Vitamin E", "items": ["Melindungi sel dari kerusakan radikal bebas", "Kesehatan kulit", "Kesehatan hormon"]},
                    {"type": "heading3", "text": "Sumber Vitamin E"},
                    {"type": "list", "items": ["Almond", "Biji bunga matahari", "Alpukat", "Bayam", "Minyak zaitun"]},
                    {"type": "text", "text": "Diet yang ada **lemak sehat** biasanya vitamin E udah masuk juga."},
                    {"type": "divider"},
                    {"type": "heading2", "text": "Haruskah makan satu per satu biar bisa memenuhi kebutuhan Vitamin?"},
                    {"type": "text", "text": "Jawabannya tidak. Karena sebenarnya lo bisa combine beberapa makanan untuk memenuhi kebutuhan vitamin lo."},
                    {"type": "text", "text": "Ada 4 kombinasi makanan yang bisa kamu coba untuk memenuhi vitamin + nutrisi lainnya:"},
                    {"type": "heading3", "text": "Kombinasi 1 — Salmon + Bayam + Alpukat"},
                    {"type": "list", "items": ["Vitamin D → salmon", "Vitamin B complex → salmon", "Vitamin K → bayam", "Vitamin C → bayam", "Vitamin E → alpukat", "Lemak sehat → salmon & alpukat"]},
                    {"type": "heading3", "text": "Kombinasi 2 — Telur + Brokoli + Nasi Merah"},
                    {"type": "list", "items": ["Vitamin D → telur", "Vitamin B complex → telur & nasi merah", "Vitamin C → brokoli", "Vitamin K → brokoli"]},
                    {"type": "heading3", "text": "Kombinasi 3 — Ayam + Paprika Merah + Alpukat"},
                    {"type": "list", "items": ["Vitamin B complex → ayam", "Vitamin C → paprika", "Vitamin E → alpukat", "Lemak sehat → alpukat"]},
                    {"type": "text", "text": "Ini juga kombinasi yang sering dipakai di *meal prep*."},
                    {"type": "heading3", "text": "Kombinasi 4 — Telur + Bayam + Jamur"},
                    {"type": "list", "items": ["Vitamin D → telur & jamur", "Vitamin K → bayam", "Vitamin B complex → telur", "Vitamin E → bayam"]},
                    {"type": "text", "text": "4 kombinasi ini adalah referensi buat kalian yang bingung harus masak apa, tapi kalau kalian bisa memenuhi kebutuhan vitamin kalian dengan cara lain juga ga masalah."},
                ],
            },
            {
                "id": "2-2",
                "type": "video",
                "title": "TDEE Calculator & Ngitung KKAL",
                "duration": "5 min",
                "content": [
                    {"type": "heading2", "text": "Resources Buat Ngitung KKAL"},
                    {"type": "video_embed", "src": "https://www.youtube.com/embed/jHhN9P0NPQA"},
                    {"type": "link_card", "href": "https://tdeecalculator.net/", "text": "🔗 Click di sini buat ke TDEE Calculator"},
                    {"type": "text", "text": "TDEE (Total Daily Energy Expenditure) Calculator digunakan untuk **menghitung total kalori yang dibakar tubuh dalam sehari**, based on umur, berat, tinggi, jenis kelamin, dan tingkat aktivitas fisik."},
                    {"type": "heading3", "text": "Kegunaan Utama TDEE Calculator"},
                    {"type": "list", "items": ["**Menurunkan Berat Badan (Defisit Calorie):** Mengetahui angka TDEE membantu lo mengonsumsi kalori di bawah angka tersebut.", "**Menambah Massa Otot (Surplus Calorie):** Memastikan lo mengonsumsi kalori lebih banyak dari TDEE untuk pertumbuhan otot.", "**Mempertahankan Berat Badan (Maintenance):** Memberikan angka pasti kalori yang harus dikonsumsi untuk menjaga berat badan saat ini.", "**Nutrition Plan:** Ngasih tau informasi soal kebutuhan makronutrien (protein, lemak, karbohidrat) harian."]},
                ],
            },
            {
                "id": "2-3",
                "type": "text",
                "title": "Supplement Needs",
                "duration": "8 min",
                "content": [
                    {"type": "callout", "icon": "⚠️", "text": "**Important:** Suplemen WHEY, GAINER, dan OMEGA 3 lo **ga wajib beli** kalau lo udah bisa memenuhinya lewat real food. Yang wajib lo beli cuma **Creatine**. Ingat — suplemen itu cuma bantu memenuhi kebutuhan lo pas lagi ga sempat atau ga bisa konsumsi dari makanan."},
                    {"type": "heading2", "text": "1. Creatine"},
                    {"type": "heading3", "text": "Muscle First Pro Creatine"},
                    {"type": "image", "src": "/supp-m1-creatine.webp", "alt": "Muscle First Pro Creatine", "size": "product"},
                    {"type": "link_card", "href": "https://shopee.co.id/MUSCLE-FIRST-Pro-Creatine-360gr-Menambah-Massa-Otot-Suplemen-Fitness-i.8802988.289998377", "text": "🛒 Beli di Shopee — Official Store"},
                    {"type": "heading3", "text": "Crevolene"},
                    {"type": "image", "src": "/supp-crevolene.webp", "alt": "Crevolene Creatine", "size": "product"},
                    {"type": "link_card", "href": "https://shopee.co.id/Evolene-NUQDgwqVE-6aMBLYLbQv6i5N5y7bC5SajqSjHPzt8UJUqbZ8a-Otot-Suplemen-Fitness-i.244776591.24157750608", "text": "🛒 Beli di Shopee — Official Store"},
                    {"type": "heading3", "text": "Provus Creatine"},
                    {"type": "image", "src": "/supp-provus-creatine.webp", "alt": "Provus Creatine", "size": "product"},
                    {"type": "link_card", "href": "https://shopee.co.id/Provus-Creatine-Matrix-300gr-(Kemasan-Lama)-Unflavored-i.1088395013.46954913369", "text": "🛒 Beli di Shopee — Official Store"},
                    {"type": "divider"},
                    {"type": "heading2", "text": "2. Omega 3"},
                    {"type": "callout", "icon": "💡", "text": "Kalau lo udah rutin konsumsi ikan, suplemen Omega 3 ini **ga perlu dibeli**."},
                    {"type": "heading3", "text": "NOW Ultra Omega 3"},
                    {"type": "image", "src": "/supp-now-omega3.webp", "alt": "NOW Ultra Omega 3", "size": "product"},
                    {"type": "link_card", "href": "https://shopee.co.id/NOW-Ultra-Omega-3-Fish-OIl-90-Softgels-i.789452017.21475465102", "text": "🛒 Beli di Shopee — Official Store"},
                    {"type": "heading3", "text": "Blackmores Fish Oil"},
                    {"type": "image", "src": "/supp-blackmores.webp", "alt": "Blackmores Fish Oil", "size": "product"},
                    {"type": "link_card", "href": "https://shopee.co.id/Blackmores-Ultimate-Omega-Odourless-Minyak-Ikan-Tidak-Berbau-1-Kapsul-Sehari-Isi-60-Kapsul-(Membantu-Memelihara-Kesehatan)-BPOM-HALAL-i.204176418.4109712057", "text": "🛒 Beli di Shopee — Official Store"},
                    {"type": "divider"},
                    {"type": "heading2", "text": "3. Gainer"},
                    {"type": "heading3", "text": "M1 Pro Gainer"},
                    {"type": "image", "src": "/supp-m1-gainer.webp", "alt": "M1 Pro Gainer", "size": "product"},
                    {"type": "link_card", "href": "https://shopee.co.id/MUSCLE-FIRST-Pro-Gainer-2lbs-900gr-Mass-Gainer-Penambah-Berat-Badan-i.8802988.896956194", "text": "🛒 Beli di Shopee — Official Store"},
                    {"type": "heading3", "text": "EVOMASS"},
                    {"type": "image", "src": "/supp-evomass.webp", "alt": "EVOMASS Gainer", "size": "product"},
                    {"type": "link_card", "href": "https://shopee.co.id/Evolene-Evomass-10-lbs-4500gr-Mass-Gainer-Suplemen-Fitness-i.244776591.7927678019", "text": "🛒 Beli di Shopee — Official Store"},
                    {"type": "heading3", "text": "Massiv Gainer"},
                    {"type": "image", "src": "/supp-massiv.webp", "alt": "Massiv Fitlife Gainer", "size": "product"},
                    {"type": "link_card", "href": "https://shopee.co.id/FITlife-Massiv-Gainer-5-lbs-2260-gram-(MPro-Upgraded)-i.180143494.7109556935", "text": "🛒 Beli di Shopee — Official Store"},
                    {"type": "heading3", "text": "Provus Gainer"},
                    {"type": "image", "src": "/supp-provus-gainer.webp", "alt": "Provus Mega Mass Gainer", "size": "product"},
                    {"type": "link_card", "href": "https://shopee.co.id/Provus-Mega-Mass-3-lb-6-Serving-Weight-Gainer-Penambah-Berat-Badan-i.6348001.23933372225", "text": "🛒 Beli di Shopee — Official Store"},
                    {"type": "divider"},
                    {"type": "heading2", "text": "4. Whey"},
                    {"type": "heading3", "text": "Whey Evolene"},
                    {"type": "image", "src": "/supp-evo-whey.webp", "alt": "Evolene EvoWhey", "size": "product"},
                    {"type": "link_card", "href": "https://shopee.co.id/Evolene-EvoWhey-Evosorption-Whey-Protein-50-Serving-1550gr-Suplemen-Fitness-i.244776591.25838061460", "text": "🛒 Beli di Shopee — Official Store"},
                    {"type": "heading3", "text": "Pro Whey"},
                    {"type": "image", "src": "/supp-pro-whey.webp", "alt": "Muscle First Pro Whey", "size": "product"},
                    {"type": "link_card", "href": "https://shopee.co.id/MUQDgwqVE-6aMBLYLbQv6i5N5y7bC5SajqSjHPzt8UJUqbZ8a-Suplemen-Fitness-i.8802988.5876940790", "text": "🛒 Beli di Shopee — Official Store"},
                    {"type": "heading3", "text": "Provus Whey"},
                    {"type": "image", "src": "/supp-provus-whey.webp", "alt": "Provus Premium Whey Gold", "size": "product"},
                    {"type": "link_card", "href": "https://shopee.co.id/Provus-Premium-Whey-Gold-900gr-Whey-Protein-Concentrate-i.1088395013.27004990140", "text": "🛒 Beli di Shopee — Official Store"},
                ],
            },
        ],
    },
    {
        "id": 3,
        "type": "static",
        "order": 3,
        "code": "MASAK",
        "title": "Template Makanan 140-145gr Protein",
        "icon_name": "ChefHat",
        "color": "from-yellow-500/20 to-yellow-500/5",
        "accent": "text-yellow-400",
        "border": "border-yellow-500/30",
        "badge": "bg-yellow-500/20 text-yellow-400",
        "locked": False,
        "comingSoon": False,
        "visible": True,
        "lessons": [
            {
                "id": "3-1",
                "type": "video",
                "title": "Template Makanan 140-145gr Protein",
                "duration": "10 min",
                "content": [
                    {"type": "image", "src": "/ch3-philip.webp", "alt": "Philip Vasquez"},
                    {"type": "callout", "icon": "🍴", "text": "**Resource: 500gr Dada Ayam & 5 Butir Telur Omega 3**"},
                    {"type": "video_embed", "src": "https://www.youtube.com/embed/UL2dtwg6-NM"},
                    {"type": "heading2", "text": "Tools that you need to maximize your nutrition needs:"},
                    {"type": "link_card", "href": "https://play.google.com/store/apps/details?id=com.fatsecret.android&hl=id", "text": "📱 FatSecret (iOS & Android) — Buat ngetrack kalori harian lo"},
                    {"type": "text", "text": "⚖️ **Penimbang berat makanan** — Buat ngitung kalori, protein, dan lain lain. *(Bisa kalian cari di Shopee / Tokopedia)*"},
                ],
            }
        ],
    },
    {
        "id": 4,
        "type": "static",
        "order": 4,
        "code": "BUILD YOUR MUSCLE",
        "title": "How To Build Your Muscle",
        "icon_name": "TrendingUp",
        "color": "from-purple-500/20 to-purple-500/5",
        "accent": "text-purple-400",
        "border": "border-purple-500/30",
        "badge": "bg-purple-500/20 text-purple-400",
        "locked": False,
        "comingSoon": False,
        "visible": True,
        "lessons": [
            {
                "id": "4-1",
                "type": "text",
                "title": "How To Build Your Muscle",
                "duration": "10 min baca",
                "content": [
                    {"type": "image", "src": "/ch4-philip.webp", "alt": "Philip Vasquez"},
                    {"type": "divider"},
                    {"type": "video_embed", "src": "https://www.youtube.com/embed/WtQPaItoDnQ"},
                ],
            }
        ],
    },
    {
        "id": 5,
        "type": "static",
        "order": 5,
        "code": "WORKOUT",
        "title": "Split Gym 3-5/Week Program",
        "icon_name": "Calendar",
        "color": "from-blue-500/20 to-blue-500/5",
        "accent": "text-blue-400",
        "border": "border-blue-500/30",
        "badge": "bg-blue-500/20 text-blue-400",
        "locked": False,
        "comingSoon": False,
        "visible": True,
        "lessons": [
            {
                "id": "5-1",
                "type": "text",
                "title": "Split Gym 3-5/Week Program",
                "duration": "10 min",
                "content": [
                    {"type": "image", "src": "/ch5-program.webp", "alt": "Program Latihan"},
                    {"type": "callout", "icon": "🎯", "text": "GOAL: Bisa menyesuaikan jadwal latihan sesuai dengan free time yang kalian punya"},
                    {"type": "heading2", "text": "Pilih Program Latihan"},
                    {
                        "type": "program_selector",
                        "programs": [
                            {
                                "id": "3x",
                                "title": "3x Per Week",
                                "subtitle": "Full Body / Upper Body & Lower Body",
                                "days": [
                                    {"day": "1. Full Body WO", "isRest": False, "exercises": [
                                        {"name": "Back Squat, Goblet Squat, atau Leg Press", "setsReps": "3 & 5-10"},
                                        {"name": "Deadlift / RDL", "setsReps": "3 & 5-10"},
                                        {"name": "Flat Bench Press / Dumbbell Press", "setsReps": "3 & 8-12"},
                                        {"name": "Bent-over Row / Cable Row", "setsReps": "3 & 8-12"},
                                        {"name": "Dumbbell / Barbell Overhead Press", "setsReps": "3 & 10-15"},
                                        {"name": "Pull-ups / Lat Pulldown", "setsReps": "3 & 8-12"},
                                        {"name": "Plank", "setsReps": "2-3 x 30s–1m"},
                                    ]},
                                    {"day": "2. Rest", "isRest": True, "exercises": [{"name": "Rest / Istirahat", "setsReps": "—"}]},
                                    {"day": "3. Upper Body WO", "isRest": False, "exercises": [
                                        {"name": "Barbell Overhead Press", "setsReps": "2 & 4-6"},
                                        {"name": "Pull Up / Lat Pull Down", "setsReps": "3 & 8-10"},
                                        {"name": "Close Grip Bench Press", "setsReps": "3 & 8-10"},
                                        {"name": "Wide Grip Seated Row × Dumbbell Lateral Raise", "setsReps": "3&12 × 3&15"},
                                        {"name": "Lower Cable Cross Over", "setsReps": "1 & 10"},
                                        {"name": "Upper Cable Cross Over", "setsReps": "1 & 10"},
                                        {"name": "Facepull / Rear Delt Fly", "setsReps": "2 × 12-15"},
                                        {"name": "Seated Bicep Curl", "setsReps": "3 × 10-12"},
                                    ]},
                                    {"day": "4. Rest", "isRest": True, "exercises": [{"name": "Rest / Istirahat", "setsReps": "—"}]},
                                    {"day": "5. Lower Body WO", "isRest": False, "exercises": [
                                        {"name": "Deadlift / RDL", "setsReps": "3 & 5-10"},
                                        {"name": "Barbell / Machine Squat", "setsReps": "3 & 5-10"},
                                        {"name": "Leg Press", "setsReps": "3 & 10-12"},
                                        {"name": "Leg Extensions", "setsReps": "3 & 10-12"},
                                        {"name": "Hip Thrust / Abduction Machine", "setsReps": "3–10-15"},
                                        {"name": "Calf Raises", "setsReps": "3 & 12"},
                                    ]},
                                    {"day": "6–7. Rest", "isRest": True, "exercises": [{"name": "Rest / Istirahat", "setsReps": "—"}]},
                                ],
                                "reminders": [
                                    "Selalu start dari warm up dulu sebelum mulai latihan beban",
                                    "Selalu fokus ke intensitas latihan",
                                    "Beban yang dimainin itu harus max sesuai dengan reps yang udah ditulis",
                                    "Selalu progressive overload 2-4 minggu sekali bisa dari set, reps, dan beban.",
                                    "Fokus latihan, kurang kurangi ngobrol.",
                                    "**Istirahat secukupnya, ga ada patokan seberapa lama lo harus beristirahat (jangan terlalu lama dan jangan terlalu cepat)**",
                                ],
                                "tips": "Kalau latihan di variasi awal dengan 3 set, make sure selalu ada 1 set untuk warm up sebanyak 10-15 reps, dan total set akan jadi 4.",
                            },
                            {
                                "id": "4x",
                                "title": "4x Per Week",
                                "subtitle": "Upper / Lower / Rest / Upper / Lower / Rest / Rest",
                                "days": [
                                    {"day": "1. Upper Body WO", "isRest": False, "exercises": [
                                        {"name": "Barbell Overhead Press", "setsReps": "2 & 4-6"},
                                        {"name": "Pull Up / Lat Pull Down", "setsReps": "3 & 8-10"},
                                        {"name": "Close Grip Bench Press", "setsReps": "3 & 8-10"},
                                        {"name": "Wide Grip Seated Row × Lateral Raise", "setsReps": "3&12 × 3&15"},
                                        {"name": "Lower Cable Cross Over", "setsReps": "1 & 10"},
                                        {"name": "Upper Cable Cross Over", "setsReps": "1 & 10"},
                                        {"name": "Facepull / Rear Delt Fly", "setsReps": "2 × 12-15"},
                                        {"name": "Seated Bicep Curl", "setsReps": "3 × 10-12"},
                                    ]},
                                    {"day": "2. Lower Body WO", "isRest": False, "exercises": [
                                        {"name": "Deadlift / RDL", "setsReps": "3 & 5-10"},
                                        {"name": "Barbell / Machine Squat", "setsReps": "3 & 5-10"},
                                        {"name": "Leg Press", "setsReps": "3 & 10-12"},
                                        {"name": "Leg Extension", "setsReps": "3 & 10-12"},
                                        {"name": "Hip Thrust / Abduction Machine", "setsReps": "3–10-15"},
                                        {"name": "Calf Raises", "setsReps": "3 & 15-20"},
                                    ]},
                                    {"day": "3. Rest", "isRest": True, "exercises": [{"name": "Rest / Istirahat", "setsReps": "—"}]},
                                    {"day": "4. Upper Body WO", "isRest": False, "exercises": [
                                        {"name": "Incline Bench Press", "setsReps": "3 & 6-8"},
                                        {"name": "Cable Fly", "setsReps": "2 & 10-12"},
                                        {"name": "Weighted Pull Up", "setsReps": "3 & 6-8"},
                                        {"name": "High Cable Lateral Raise", "setsReps": "2-3 & 8-10"},
                                        {"name": "Deficit Pendlay Row", "setsReps": "2 & 6-8"},
                                        {"name": "Cable Overhead Tricep Extension", "setsReps": "2 & 8-10"},
                                        {"name": "Bayesian Curl", "setsReps": "2 & 8-10"},
                                    ]},
                                    {"day": "5. Lower Body WO", "isRest": False, "exercises": [
                                        {"name": "Deadlift / RDL", "setsReps": "4 & 5-10"},
                                        {"name": "Leg Press", "setsReps": "4 & 10-12"},
                                        {"name": "Hip Thrust / Abduction Machine", "setsReps": "3 & 8-10"},
                                        {"name": "Slow Eccentric Leg Extension", "setsReps": "3 & 8-10"},
                                        {"name": "Calf Raises", "setsReps": "4 × 15-20"},
                                        {"name": "Leg Raises", "setsReps": "3 × 10-20"},
                                    ]},
                                    {"day": "6–7. Rest", "isRest": True, "exercises": [{"name": "Rest / Istirahat", "setsReps": "—"}]},
                                ],
                                "reminders": [
                                    "Selalu start dari warm up dulu sebelum mulai latihan beban",
                                    "Selalu fokus ke intensitas latihan",
                                    "Beban yang dimainin itu harus max sesuai dengan reps yang udah ditulis",
                                    "Selalu progressive overload 2-4 minggu sekali bisa dari set, reps, dan beban.",
                                    "Fokus latihan, kurang kurangi ngobrol.",
                                    "**Istirahat secukupnya, ga ada patokan seberapa lama lo harus beristirahat (jangan terlalu lama dan jangan terlalu cepat)**",
                                ],
                                "tips": "Kalau latihan di variasi awal dengan 3 set, make sure selalu ada 1 set untuk warm up sebanyak 10-15 reps, dan total set akan jadi 4.",
                            },
                            {
                                "id": "5x",
                                "title": "5x Per Week",
                                "subtitle": "Push / Pull / Legs & Shoulder / Rest / Upper / Lower / Rest",
                                "days": [
                                    {"day": "1. Push", "isRest": False, "exercises": [
                                        {"name": "Incline Bench Press", "setsReps": "3 & 6-8"},
                                        {"name": "Flat Bench Press", "setsReps": "3 & 8-10"},
                                        {"name": "Weighted Dips", "setsReps": "3-4 & 10-12"},
                                        {"name": "Pec Deck Fly", "setsReps": "3-4 & 12"},
                                        {"name": "Overhead Tricep Extension", "setsReps": "3 & 10-12"},
                                        {"name": "Single Arm Tricep Push Down", "setsReps": "3 & 12-15"},
                                        {"name": "Reserve Grip Tricep Push Down", "setsReps": "3 & 10-12"},
                                        {"name": "Ab Crunch Machine", "setsReps": "3 & 12-15"},
                                    ]},
                                    {"day": "2. Pull", "isRest": False, "exercises": [
                                        {"name": "Lat Pull Down", "setsReps": "2-3 & 6-8"},
                                        {"name": "Reserve Grip LPD", "setsReps": "2-3 & 8-10"},
                                        {"name": "1 Arm Seated Cable Row", "setsReps": "3 & 10-12"},
                                        {"name": "Cable Straight Arm Pull Down", "setsReps": "3 & 10-12"},
                                        {"name": "Seated Bicep Curl", "setsReps": "3–10-12"},
                                        {"name": "T-Bar Bicep Curl", "setsReps": "3 & 8-10"},
                                        {"name": "Cable Hammer Curl", "setsReps": "3 & 10-15"},
                                    ]},
                                    {"day": "3. Leg & Shoulder", "isRest": False, "exercises": [
                                        {"name": "Deadlift", "setsReps": "2-3 & 6-8"},
                                        {"name": "Squat", "setsReps": "2-3 & 6-10"},
                                        {"name": "Leg Extension (optional)", "setsReps": "3 & 10-15"},
                                        {"name": "Lateral Raise", "setsReps": "3-4 & 10-15"},
                                        {"name": "Overhead DBL Press / Barbell Overhead Press", "setsReps": "3 & 8-10"},
                                        {"name": "Rear Delt Fly / Face Pull", "setsReps": "3 & 12-15"},
                                        {"name": "Shrugs", "setsReps": "3-4 & 12-15"},
                                    ]},
                                    {"day": "4. Rest", "isRest": True, "exercises": [{"name": "Rest / Istirahat", "setsReps": "—"}]},
                                    {"day": "5. Upper Body WO", "isRest": False, "exercises": [
                                        {"name": "Incline Barbell Bench Press", "setsReps": "3 & 6-8"},
                                        {"name": "Cable Fly", "setsReps": "2 & 10-12"},
                                        {"name": "Weighted Pull Up", "setsReps": "3 & 6-8"},
                                        {"name": "High Cable Lateral Raise", "setsReps": "2-3 & 8-10"},
                                        {"name": "Deficit Pendlay Row", "setsReps": "2 & 6-8"},
                                        {"name": "Cable Overhead Tricep Extension", "setsReps": "2 & 8-10"},
                                        {"name": "Bayesian Curl", "setsReps": "2 & 8-10"},
                                    ]},
                                    {"day": "6. Lower Body WO", "isRest": False, "exercises": [
                                        {"name": "Deadlift / RDL", "setsReps": "3 & 6-10"},
                                        {"name": "Leg Press", "setsReps": "3-4 & 10-12"},
                                        {"name": "Hip Thrust / Abduction Machine", "setsReps": "3 & 8-10"},
                                        {"name": "Slow Eccentric Leg Extension", "setsReps": "3 & 8-10"},
                                        {"name": "Calf Raises", "setsReps": "4 × 15-20"},
                                        {"name": "Leg Raises", "setsReps": "3 × 10-20"},
                                    ]},
                                    {"day": "7. Rest", "isRest": True, "exercises": [{"name": "Rest / Istirahat", "setsReps": "—"}]},
                                ],
                                "reminders": [
                                    "Selalu start dari warm up dulu sebelum mulai latihan beban",
                                    "Selalu fokus ke intensitas latihan",
                                    "Beban yang dimainin itu harus max sesuai dengan reps yang udah ditulis",
                                    "Selalu progressive overload 2-4 minggu sekali bisa dari set, reps, dan beban.",
                                    "Fokus latihan, kurang kurangi ngobrol.",
                                    "**Istirahat secukupnya, ga ada patokan seberapa lama lo harus beristirahat (jangan terlalu lama dan jangan terlalu cepat)**",
                                ],
                                "tips": "Kalau latihan di variasi awal dengan 3 set, make sure selalu ada 1 set untuk warm up sebanyak 10-15 reps, dan total set akan jadi 4.",
                            },
                        ],
                    },
                    {"type": "callout", "icon": "⚠️", "text": "**NOTE:** Setelah lo pilih program latihan, make sure keep it consistent sampai 3 bulan kalau lo mau hasilnya maksimal. Kalau ada masalah, langsung tag **@cenhfits** di VIP community — gw bakalan jawab semua kebutuhan kalian untuk progress bentukin otot."},
                ],
            }
        ],
    },
    {
        "id": 6,
        "type": "static",
        "order": 6,
        "code": "FINAL",
        "title": "FINAL — Your Next Step",
        "icon_name": "Flag",
        "color": "from-orange-500/20 to-orange-500/5",
        "accent": "text-orange-400",
        "border": "border-orange-500/30",
        "badge": "bg-orange-500/20 text-orange-400",
        "locked": False,
        "comingSoon": False,
        "visible": True,
        "lessons": [
            {
                "id": "6-1",
                "type": "video",
                "title": "FINAL — Your Next Step",
                "duration": "15 min",
                "content": [
                    {"type": "video_embed", "src": "https://www.youtube.com/embed/eUpr3wGOm3A"},
                ],
            }
        ],
    },
    {
        "id": 7,
        "type": "static",
        "order": 7,
        "code": "GYM MYTH",
        "title": "Gym Myths Debunked",
        "icon_name": "Zap",
        "color": "from-pink-500/20 to-pink-500/5",
        "accent": "text-pink-400",
        "border": "border-pink-500/30",
        "badge": "bg-pink-500/20 text-pink-400",
        "locked": True,
        "comingSoon": True,
        "visible": True,
        "lessons": [],
    },
]


async def main():
    mongo_url = os.environ['MONGO_URL']
    db_name = os.environ['DB_NAME']
    client = AsyncIOMotorClient(mongo_url)
    db = client[db_name]

    print(f"Connecting to {db_name}...")
    inserted = 0
    updated = 0
    for ch in CHAPTERS:
        result = await db.chapters.update_one(
            {"id": ch["id"], "type": "static"},
            {"$set": ch},
            upsert=True,
        )
        if result.upserted_id:
            inserted += 1
            print(f"  + Inserted chapter {ch['id']}: {ch['title']}")
        else:
            updated += 1
            print(f"  ~ Updated chapter {ch['id']}: {ch['title']}")

    total = await db.chapters.count_documents({})
    print(f"\nDone. {inserted} inserted, {updated} updated. Total chapters in DB: {total}")
    client.close()


if __name__ == "__main__":
    asyncio.run(main())
